version: '3'
services:
  restaurant-service:
    image: localhost:5000/diegotobon2000/restaurant-service:PACKT-SNAPSHOT
    ports:
      - "8080:8080"

  booking-service:
    image: localhost:5000/diegotobon2000/booking-service:PACKT-SNAPSHOT
    ports:
      - "8081:8080"

  user-service:
    image: localhost:5000/diegotobon2000/user-service:PACKT-SNAPSHOT
    ports:
      - "8082:8080"